### ISSUE TITLE
Wrong parameter order

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-rainmaker-android#23]
There is wrong parameters order inside device tab. Parameter "Name" is always first. 
Problem on Android app only.
App version: 2.6.1 - 5ecc246

**Comment by jacek12345** [comment]
> Hi @jacek12345 , Param with type "esp.param.name" will be displayed first.

Hi @khushbushah2302 ,
Thank You for response.
Why this is always first displayed? This is less important parameter, as used for customisation name only. It is changed very seldom by user, usually ones. 
It could be great, that developer decides about parameters order, like in Your iOS app.
Please consider the change.
Although I have not yet started analyzing the sources of the application, for the time being I am dealing with the device software and only reporting irregularities. Please tell me, will it be easy to change the display order when I create my own version of the application?

**Comment by khushbushah2302** [comment]
Hi @jacek12345 ,

Name parameter has special treatment in RainMaker
1. It gets added automatically when you use any standard device creation APIs in firmware.
2. It's value is not just shown in param list screen like other params, but also used as the name in device list screen and header in device params screen.
3. It is reported separately to Alexa/GVA as well.

That is the reason why it is shown at top in the list.

Even then, what you are saying is also right and the param can be moved to the bottom or elsewhere as desired, with minor changes in code. Since the phone app sources are open, you can even move it to the device info page instead of having it in param list.

Thanks.

**Comment by jacek12345** [comment]
Thank You for explanation. So I'll do it myself. I will back if have any troubles with it.
