### ISSUE TITLE
I have some doubts, please clarify...  

### ISSUE THREAD

**Issue by nravin5** [espressif/esp-rainmaker-android#26]
1. can we publish this app after customization ac per our brand...
2. min sdk requirement ask by google is 31, so you update it...
3. can we commercially use this app only after changing brand logo and brand name...

Thanks in advance.

**Comment by shahpiyushv** [comment]
> 1. can we publish this app after customization ac per our brand...

Yes, indeed.

> 2. min sdk requirement ask by google is 31, so you update it...

We will update the Android Target API level to 31.

> can we commercially use this app only after changing brand logo and brand name...

Phone apps are just one part. To use RainMaker for commercial purposes, you will have to get a private RainMaker deployment first, since the public RainMaker is meant only for evaluation and hobby purposes. Your customised app will then talk to this private deployment. Please send an email to sales@espressif.com for additional info.
