### ISSUE TITLE
Option to make group of different devices from different node

### ISSUE THREAD

**Issue by nravin5** [espressif/esp-rainmaker-android#31]
1. Currently we can make group of nodes only, this means all the devices under the node comes under the group but when we want some of devices from one node and some of from other nodes comes in a group it is not possible. But in Alexa app we can do these type of grouping....if this is possible in future updates this is very appreciable.

2. one another thing....please give a option to add name to node id,  it is very difficult to recognize with node id.... 

3. Thanks for adding Device automation feature, 
   Please also add location automation, though which we can trigger any device though location data...eg. when we reach near our home AC will turn on.... 

Thanks in advance.

**Comment by shahpiyushv** [comment]
@nravin5 , the feature requests are quite valid, but please see my comments on these

> Currently we can make group of nodes only, this means all the devices under the node comes under the group but when we want some of devices from one node and some of from other nodes comes in a group it is not possible. But in Alexa app we can do these type of grouping....if this is possible in future updates this is very appreciable.

The primary addressable entity in RainMaker is node (identified by the node id). All access control is governed by the node id and user id. Even if there are multiple devices under a node, the cloud still considers it as a single entity because it is agnostic to the data in node config and params. When you share a node or a group, the cloud backend modifies the access control data based on node id and that is the reason, why we don't have grouping based on devices.

> one another thing....please give a option to add name to node id, it is very difficult to recognize with node id....

Since most nodes have single device and the associated device name, we did not have any editable node name as such. We can consider adding an optional ["service"](https://rainmaker.espressif.com/docs/spec-concepts.html#services) for this in future, which people can add for multi device nodes.

> Thanks for adding Device automation feature, Please also add location automation, though which we can trigger any device though location data...eg. when we reach near our home AC will turn on....

This would indeed be a good feature for many, but currently we are refraining from tracking users' home and current location for privacy reasons. Location permission asked during provisioning is just used for the Wi-Fi/BLE calls. We will consider this feature in future though.
