### ISSUE TITLE
Node Group Sharing doesn't send notification to invited user, hence can't accept request.

### ISSUE THREAD

**Issue by Fahadk7** [espressif/esp-rainmaker-android#41]
Hi, @shahpiyushv 

We have been using the public Rainmaker and will soon go for private deployment.

However, while customizing the Android apps we came across an issue. We intend to share the whole Home-Room structure with another user and use the latest node group sharing APIs to do the same. However the invited user does not receive the notification or the request ID, and he cannot accept the invite.

Sharing a single node works flawlessly and the user gets the notification, but sharing the whole node group doesn't work.

Also, just like to know if there is any way to get the list of users associated with the node?
I see the option for getting the list of nodes associated with the user but we need to know how many users have access to a particular node and then display that in each end user's app, (primary or secondary)

**Comment by Fahadk7** [comment]
Hi
Just following up on this issue, since the rainmaker app doesnt give any notification for a whole group of nodes shared to another user

Awaiting your response.

**Comment by shahpiyushv** [comment]
@Fahadk7 , Since the public RainMaker apps did not support handling of group sharing notifications, these were not enabled in the public deployment. However, now we have enabled those and you can try them in your app.

Meanwhile, you can use [GET /user/nodes/sharing ](https://swaggerapis.rainmaker.espressif.com/#/User%20Node%20Association/getUserNodeSharing) with node_id as query parameter to get a list of users linked to that node.

**Comment by KhushbuShah25** [comment]
Hey @Fahadk7 , group sharing feature is available now in latest release so user can accept / decline group sharing request from notification and from app.
